version: "3.7"

x-db-envvars: &db-envvars
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  POSTGRES_DB: ${DB_NAME}
  POSTGRES_USER: ${DB_USER}
  POSTGRES_PASSWORD: ${DB_PASS}

x-default-envvars: &default-envvars
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DJANGO_SETTINGS_MODULE: settings.develop

x-default-app: &default-app
  build:
    .
  volumes:
    - ./src:/app
  environment:
    <<: *default-envvars


services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
      target: "development"
    command: [ "sh", "/scripts/start-dev-server.sh" ]
    volumes:
      - ./src:/app
    environment:
      <<: *default-envvars
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - django-starter-db:${DB_DATA}
    environment:
      <<: *db-envvars

  redis:
    image: redis:latest
    ports:
     - "6379:6379"

volumes:
  django-starter-db:
  app:
  
